name: Deploy by Pulling on Server

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🔃 Directory change."
            cd ${{ secrets.WORK_DIR }}

            echo "🏃 Git pull start."
            git pull origin main
            echo "🏃 Git pull finished."

            echo "🏃 NPM install start."
            npm install
            echo "🏃 NPM install finished."

            echo "🏃 TailwindCSS build start."
            npx @tailwindcss/cli -i ./global.css -o ./tailwind.css
            cp tailwind.css ${{ secrets.CSS_DIR }}
            echo "🏃 TailwindCSS build finished."

            echo "👍 Task finished."
